updated login design
chico1992/alumni pull request #17
Opened 2018-08-14 14:59 UTC by devo05

2018-08-14 17:51 UTC, chico1992 requested changes
could you fix your indentation 4 spaces instead of 2 and then everything should be fine for me

2018-08-14 20:14 UTC, chico1992 approved these changes
fine for me thanks

2018-08-14 20:36 UTC, damicnic reviewed
fixed

2018-08-15 10:21 UTC, bobwebninja approved these changes
👍

2018-08-15 18:05 UTC, merged