Signup (part 2)
chico1992/alumni pull request #18
Opened 2018-08-15 13:20 UTC by mklepper

added handling of unique invitation id on signup, and the to implementation of roles and the visibilityGroups of the invitation upon signup.

2018-08-15 13:28 UTC, chico1992 requested changes
hi max looks good but could you add a part that the invitation is deleted and can you tell me if we check that the username is unique and the email?
could you also add a part to your code to handle an invalid invitation to let the user know and can you handel a check that the email entered by the user is the same as in the invitation?

2018-08-15 14:51 UTC, mklepper commented
Ok, I will look into the requested changes

2018-08-16 09:02 UTC, chico1992 approved these changes

2018-08-16 09:28 UTC, anastasiakotolupova approved these changes
seems good

2018-08-16 09:29 UTC, merged